mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# from mysite.views import *
from books import views
# from contact.views import contact


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^hello/$', hello),
    # url(r'^time/$', current_datetime),
    # url(r'^time/plus/(\d{1,2})/$', hour_ahead),
    # url(r'^search-form/$', views.search_form),
    # url(r'^search/$', views.search),
    # url(r'^contact/$', contact)

)

urlpatterns += patterns('mysite.views',
                        url(r'^hello/$', 'hello'),
                        url(r'^time/$', 'current_datetime'),
                        url(r'^time/plus/(\d{1,2})/$', 'hour_ahead'),

                        )

urlpatterns += patterns('contact.views',
                        url(r'^contact/$', 'contact')
                        )

books/models.py
from django.db import models

# Create your models here.

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    num_page = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return self.title

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message =self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words")
        return message

books/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect
from books.models import Book
from django.core.mail import send_mail


# Create your views here.

def search_form(request):
    return render_to_response("search_form.html")

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('search_results.html', {'books': books, 'query': q})

    return render_to_response('search_form.html', {'errors': errors})

contact/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.core.mail import send_mail
from contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@hotmail.com_'),
                ['siteowner@hotmail.com_']

            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial = {'subject': 'I love your site!'}
            )
    return render_to_response('contact_form.html', {'form': form})

mysite/views.py
from django.http import HttpResponse, Http404
import datetime
from django.shortcuts import render_to_response



def hello(request):
    return HttpResponse("Hello World")

def current_datetime(request):
    now = datetime.datetime.now()
    # t = get_template('current_date.html')
    # t = Template("<html><body>It is now {{ current_date }}.</body></html>")
    # html = t.render(Context({'current_date': now}))
    return render_to_response('current_date.html', {'current_date': now})

def hour_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
    #assert False
    html = "<html><body>In %s hour(s), it will be %s.</body></html>" % (offset, dt)
    return HttpResponse(html)

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

templates/contact_form.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>
    {% if forms.error %}
        <p style="color: red;">
        please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form action="/contact/" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="field">Message:</label>
            {{ form.message }}
        </div>
    </form>

</body>
</html>

templates/current_date.html
{% extends "base.html" %}

{% block title %} the current time {% endblock %}

{% block content %}
<p>It is now {{ current_data }}</p>
{% endblock %}

templates/hours_ahead.html
{% extends "base.html" %}

{% block title %} Future time{% endblock %}

{% block content %}
<p>in {{ hour_offset }} hour(s), it will be {{ next_time }}</p>
{% endblock %}

templates/search_form.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    {% if errors %}
        <ul>
        {% for error in errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>

</body>
</html>

templates/search_results.html
<p>You search for : <stron>{{ query }}</stron></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
            <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria</p>
{% endif %}